# Authors to add:
puts 'English - '
puts 'French - '
puts 'German - '
puts 'Italian - Alfonso Varano, Arnaldo Fusinato'
puts 'Portuguese - Caetano Veloso, Alda do Espirito Santo, Angélica Freitas, Ricardo Domeneck'
puts 'Spanish - Antonio Machado'
puts ' '
# Sources to use:
puts 'SOURCES:'
puts 'English: Poetry Foundation, poets.org'
puts 'French: frenchPoems-francaise.fr, unjourunpoeme.fr'
puts 'German: deutschelyrik.de'
puts 'Italian: www.poesie.reportonline.it'
puts 'Spanish: poemas-del-alma.com, culturacolectiva.com, poesi.as'
puts 'Portuguese: Modo de usar e co, Escamandro'
